Implementing codecov testing

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -1,14 +1,47 @@
 ---
-
 name: Check with Codecov
 on:
+  push:
+    branches:
+      - development
   pull_request:
     branches:
-      - 'deployment'
+      - development
 
 jobs:
-  check-codecov:
-    - name: Upload coverage reports to Codecov
-    uses: codecov/codecov-action@v3
-    env:
-      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  codecov:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.22.3'
+
+      - name: Install dependencies
+        run: go mod tidy
+
+      - name: Run tests and generate coverage report
+        run: go test ./... -coverprofile=coverage.txt -covermode=count
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v4.3.1
+        with:
+          files: ./coverage.txt
+          fail_ci_if_error: true
+          verbose: true
+        env:
+           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Check coverage percentage
+        run: |
+          coverage=$(go tool cover -func=coverage.txt | grep total: | awk '{print $3}')
+          echo "Coverage is $coverage"
+          required_coverage="90.0%"
+          if [[ "$(echo "$coverage" | sed 's/%//')" < "$(echo "$required_coverage" | sed 's/%//')" ]]; then
+            echo "Coverage is below 90%. Failing the build."
+            exit 1
+          fi
+        shell: bash
